# docker-compose.yml
version: '3.10'

networks:
  ml-network:
    driver: bridge

volumes:
  model-storage:
  mlruns-storage:
  reports-storage:
  grafana_data:
  prometheus_data:

services:
  ml-backend:
    build:
      context: .
      dockerfile: Dockerfile.dockerfile
    container_name: health-ml-backend
    ports:
      - "8000:8000"
    volumes:
      - ./models:/app/models
      - ./mlruns:/app/mlruns
      - ./reports:/app/reports
      - ./data:/app/data
    environment:
      - ENVIRONMENT=development
      - MLFLOW_TRACKING_URI=./mlruns
      - PYTHONPATH=/app
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health"]
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 60s   # tambahin waktu tunggu startup
    networks:
      - ml-network

  prometheus:
    image: prom/prometheus:latest
    container_name: health-ml-prometheus
    ports:
      - "9090:9090"
    volumes:
      - ./monitoring/prometheus.yaml:/etc/prometheus/prometheus.yaml
      - prometheus_data:/prometheus
    extra_hosts:
      - "host.docker.internal:host-gateway" 
    networks:
      - ml-network

  grafana:
    image: grafana/grafana:latest
    container_name: health-ml-grafana
    ports:
      - "3000:3000"
    environment:
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD=admin
    volumes:
      - grafana_data:/var/lib/grafana
      - ./monitoring/grafana/provisioning:/etc/grafana/provisioning
    networks:
      - ml-network
    depends_on:
      - prometheus

  ml-frontend:
    build:
      context: .
      dockerfile: Dockerfile.streamlit.dockerfile
    container_name: health-ml-frontend
    ports:
      - "8501:8501"
    volumes:
      - ./models:/app/models
      - ./mlruns:/app/mlruns
      - ./reports:/app/reports
      - ./data:/app/data
    environment:
      - BACKEND_URL=http://ml-backend:8000
      - ENVIRONMENT=development
    depends_on:
      ml-backend:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8501/_stcore/health"]
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 40s
    networks:
      - ml-network

  mlflow-ui:
    image: python:3.10-slim
    container_name: health-mlflow-ui
    ports:
      - "5000:5000"
    working_dir: /app
    command: >
      sh -c "pip install mlflow && 
             mlflow ui --host 0.0.0.0 --port 5000 --backend-store-uri file:/app/mlruns"
    volumes:
      - ./mlruns:/app/mlruns
    depends_on:
      - ml-backend
    networks:
      - ml-network

  monitoring:
    build:
      context: .
      dockerfile: Dockerfile.streamlit.dockerfile
    container_name: health-ml-monitoring
    ports:
      - "8502:8501"
    volumes:
      - ./models:/app/models
      - ./mlruns:/app/mlruns
      - ./reports:/app/reports
      - ./data:/app/data
    environment:
      - ENVIRONMENT=development
      - BACKEND_URL=http://ml-backend:8000
    depends_on:
      ml-backend:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8501/_stcore/health"]
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 40s
    networks:
      - ml-network